server:
  port: ${CONFIG_SERVER_PORT:8061}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8081}/eureka/

spring:
  application:
    name: config-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/toopoo/config.git
          searchPaths: /
          username: zhoutaoo
          password: 5563557zztt029
  zipkin:
    baseUrl: http://localhost:8091

management:
  endpoints:
    web:
      exposure:
        include: '*'