version: '3'
services:
  sentinel-dashboard:
    image: cike/sentinel-dashboard-docker:latest
    container_name: sc-sentinel-dashboard
    restart: always
    networks:
      - sc-net
    ports:
      - 8021:8021
    env_file: .env
