spring:
  application:
    name: eureka-server
server:
  port: 9002
eureka:
  instance:
    hostname: host2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://host1:9001/eureka/