spring:
  application:
    name: eureka-server
server:
  port: 9001
eureka:
  instance:
    hostname: host1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://host2:9002/eureka/