server:
  port: 8041

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8081}/eureka/

spring:
  application:
    name: feign-consumer
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  boot:
    admin:
      url: http://${BOOT_ADMIN_HOST:localhost}:${BOOT_ADMIN_PORT:8022}
  zipkin:
    sender:
      type: rabbit
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
    feign:
      enabled: true
      processor:
        enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "3MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#  compression:
#    response:
#      enabled: true
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

logging:
  level:
    org.springframework.cloud.sleuth: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'